name: deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Meteor.js environment
        uses: meteorengineer/setup-meteor@v1.0.3
      
      - name: Create deployment token file from secret
        run: printf "$METEOR_SESSION_TOKEN_JSON" > token.json
        env:
          METEOR_SESSION_TOKEN_JSON : ${{ secrets.METEOR_SESSION_TOKEN_JSON }}
          
      - name: Meteor login
        run: meteor login

      - name: Meteor deploy
        run: meteor deploy anoop901-todo.meteorapp.com
